/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Copyright (C) 2026 emexlab
 *
 * This file is part of emex64.
 *
 * emex64 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * emex64 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with emex64. If not, see <https://www.gnu.org/licenses/>.
 */

#include <EmexToolchain/ETCompiler/ETCompilerCodegen.h>

EFStringRef ETCompilerCodegenCreateASMSourceWithAST(ETCompilerASTNodeRef node)
{
    if(node == NULL)
    {
        return NULL;
    }

    EFAUTOREL EFMutableStringRef asmSource = EFStringCreateMutableCopy(kEFAllocatorDefault, EFSTR("; code generated by the emex64 C compiler\n\n"));
    if(asmSource == NULL)
    {
        return NULL;
    }

    /* handle file scope variables */
    {
        EFAUTOREL EFMutableStringRef dataSectionSource = EFStringCreateMutableCopy(kEFAllocatorDefault, EFSTR("section .data\n"));
        EFAUTOREL EFMutableStringRef bssSectionSource = EFStringCreateMutableCopy(kEFAllocatorDefault, EFSTR("section .bss\n"));
        if(dataSectionSource == NULL || bssSectionSource == NULL)
        {
            return NULL;
        }

        EFAUTOREL EFArrayRef children = ETCompilerASTNodeCopyChildren(kEFAllocatorDefault, node);
        for(EFIndex index = 0; index < EFArrayGetCount(children); index++)
        {
            ETCompilerASTNodeRef child = EFArrayGetValueAtIndex(children, index);
            if(ETCompilerASTNodeGetKind(child) == kETCompilerASTNodeKindVarDecl)
            {
                EFAUTOREL EFArrayRef declaration = ETCompilerASTNodeCopyChildren(kEFAllocatorDefault, child);

                //ETCompilerASTNodeRef typeRef = EFArrayGetValueAtIndex(declaration, 0); /* MARK: will later become important */
                ETCompilerASTNodeRef integerLiteralRef = EFArrayGetValueAtIndex(declaration, 1);

                if(integerLiteralRef == NULL)
                {
                    EFStringAppendFormat(bssSectionSource, EFSTR("  %@ dq 1\n"), ETCompilerTokenGetString(ETCompilerASTNodeGetToken(child)));
                }
                else
                {
                    EFStringAppendFormat(dataSectionSource, EFSTR("  %@ dq %@\n"), ETCompilerTokenGetString(ETCompilerASTNodeGetToken(child)), ETCompilerTokenGetNumber(ETCompilerASTNodeGetToken(integerLiteralRef)));
                }
            }
        }

        EFStringAppendFormat(asmSource, EFSTR("%@\n%@"), dataSectionSource, bssSectionSource);
    }

    return EFAUTOTRANSFER(asmSource);
}
